name: Deploy to Heroku
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Heroku auth
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku auth:token >/dev/null 2>&1 || true
          heroku whoami || heroku auth:token >/dev/null

      - name: Set Heroku git remote
        run: heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}

      - name: Deploy (push to Heroku remote)
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:main -f

      - name: Smoke test
        if: always()
        run: |
          sleep 10
          curl -sSf https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/api/health | grep '"ok":'
